name: CI/CD for Next.js

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Replace with the appropriate Node.js version

      - name: Install dependencies
        run: yarn install

      - name: Build Next.js app
        run: yarn build

      - name: Install Surge
        run: npm install -g surge

      - name: Deploy to Surge
        run: surge ./build streamit.surge.sh --token ${{ secrets.SURGE_LOGIN }}
