name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' # Specify the version as a string ('20' instead of 20)

    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
      
    - name: Build React App
      run: yarn build
      
    - name: Install Surge
      run: npm install -g surge
      
    - name: Deploy to surge
      run: surge ./build streamit.surge.sh --token ${{secrets.SURGE_LOGIN}}
